version: "3.7"

services:
    postgres:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=user
            - POSTGRES_DB=user

    backend:
        build: ./backend
        volumes:
        - static_data:/vol/web/static
        - media_data:/vol/web/media
        env_file: 
        - ./.env.dev
        depends_on: 
        - postgres

    frontend:
        tty: true
        build: ./frontend
        command: ["npm","run-script","build"]
        volumes:
        - ./frontend:/usr/src/frontend

    redis:
        restart: always
        image: redis:latest
        ports:
        - "6379:6379"
        volumes:
        - redisdata:/data
            
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - static_data:/vol/web/static
            - media_data:/vol/web/media
            - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./frontend/build:/var/www/frontend # maps frontend build inside nginx
            - ./certs:/etc/nginx/certs
            - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
        depends_on:
            - backend

volumes:
    static_data:
    media_data:
    postgres_data:
    redisdata: