version: "3.7"

services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=user

  backend:
    build: ./backend
    ports: 
      - "8000:8000"
    volumes:
      - ./backend/:/usr/src/backend/
    command: python manage.py runserver 0.0.0.0:8000
    env_file: 
      - ./.env.dev
    depends_on: 
      - postgres

  frontend:
    tty: true
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/usr/src/frontend
    ports:
      - "3000:3000"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  postgres_data:
  pgdata:
  redisdata:


            