from celery import shared_task,task
from django.core.mail import send_mail
from datetime import datetime, timedelta
from .models import Notifications
from rest_framework_simplejwt.token_blacklist.management.commands import flushexpiredtokens

last_month = datetime.today() - timedelta(days=30)

@task()
def flush_notifications():
	print('theres noti to be deleted')

	return None

@task()
def flush_tokens():
	print('we in cron bro for tokens')
	return None

@shared_task
def send_mail_task(email,preview):
	send_mail('NOBO CRM Notification',
          	str(preview) + ' Do not reply , this is an autogenerated message',
          	'dionneo123@gmail.com',
          	[email],
          	fail_silently=False)
	return None